{% set name = "drawdata" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/koaning/{{ name }}/archive/refs/tags/{{ version }}.tar.gz 
  sha256: 980aeaf71cb3c1ca0feafa5e1168b43356684d4202a4ec14cad6005647598f3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - ipython >=7.16.1
    - jupyter >=1.0.0
    - python >=3.7
    - anywidget

test:
  imports:
    - drawdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://calmcode.io/labs/drawdata.html
  dev_url: https://github.com/koaning/drawdata
  summary: Draw a dataset in a jupyter notebook.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
