{% set name = "drawdata" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/koaning/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: a2d62fb3254e4194e97d4687d904c35a1eebf8faf9966641cc4f479fa2a222ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - ipython >=7.16.1
    - jupyter >=1.0.0
    - python >={{ python_min }}
    - anywidget

test:
  imports:
    - drawdata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://calmcode.io/labs/drawdata.html
  dev_url: https://github.com/koaning/drawdata
  summary: Draw a dataset in a jupyter notebook.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
