{% set name = "drawdata" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/koaning/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 626599dabc0c3f5a2d3cec94aaf59cec403888e4737d27717c188261d235dec0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - ipython >=7.16.1
    - jupyter >=1.0.0
    - python >={{ python_min }}
    - anywidget

test:
  imports:
    - drawdata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://calmcode.io/labs/drawdata.html
  dev_url: https://github.com/koaning/drawdata
  summary: Draw a dataset in a jupyter notebook.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
